export '../../app/initial_screen.dart';
export '../../app/intro_slider/views/intro_page.dart';
export '../../app/authentication/views/login.dart';
export '../../app/authentication/views/jobseeker_signup.dart';
export '../../app/authentication/views/company_signup.dart';
export '../../app/authentication/views/user_identification.dart';
export '../../app/dashboard/company/views/company_dashboard.dart';
export '../../app/dashboard/recruiter/views/recuiter_dashboard.dart';
export '../../app/dashboard/jobseeker/views/jobs_dashboard.dart';
